/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.List;
import Modal.ThongKe;
import DAO.ThongKeDao;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.jfree.chart.*;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author admin
 */
public class ThongKe_Panel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLi_JPanel
     */
    public ThongKe_Panel() {
        initComponents();
        init();
    }

    void changeForm(JPanel pn) {
        ChartPannel.removeAll();
        ChartPannel.add(pn);
        ChartPannel.repaint();
        ChartPannel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ChartPannel = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        content.setPreferredSize(new java.awt.Dimension(1142, 772));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Sản Phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        content.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton2.setText("Dịch Vụ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        content.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 22, -1, -1));

        jButton3.setText("Doanh Thu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        content.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 22, -1, -1));

        jButton4.setText("In");
        content.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(938, 22, -1, -1));

        ChartPannel.setBackground(new java.awt.Color(255, 102, 51));
        ChartPannel.setLayout(new javax.swing.BoxLayout(ChartPannel, javax.swing.BoxLayout.LINE_AXIS));
        content.add(ChartPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 63, 1100, 690));

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        content.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChartSP();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        chartDV();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       chartDT();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       //tao chart
       List<ThongKe> list = ThongKeDao.DoanhThu();
        DefaultCategoryDataset jfchart = new DefaultCategoryDataset();
        //them du lieu
        for (int i = 0; i < list.size(); i++) {
            jfchart.setValue(list.get(i).getValue(), "ngày", list.get(i).getName());
        }
        //dua chart vao panel
        JFreeChart chart = ChartFactory.createLineChart("aa", "a", "aa", jfchart);

        //setup chart
        ChartPanel c = new ChartPanel(chart);
        c.setSize(ChartPannel.getWidth(), ChartPannel.getHeight());
        c.setMouseWheelEnabled(false);
        
//       p.setLayout(new java.awt.BorderLayout());
        //update panel
        ChartPannel.removeAll();
        ChartPannel.add(c, BorderLayout.CENTER);
        ChartPannel.validate();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChartPannel;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
    List<ThongKe> sp;
    List<ThongKe> dv;
    List<ThongKe> thongke;

    void Chart(String Title, String Name, String Stringvalue, List<ThongKe> list) {
        //tao chart
        DefaultCategoryDataset jfchart = new DefaultCategoryDataset();
        //them du lieu
        for (int i = 0; i < list.size(); i++) {
            jfchart.setValue(list.get(i).getValue(), Stringvalue, list.get(i).getName());
        }
        //dua chart vao panel
        JFreeChart chart = ChartFactory.createBarChart(Title, Name, Stringvalue, jfchart);
//        chart.setBackgroundPaint(Color.yellow);
        chart.setBorderVisible(false);
        
        CategoryPlot pilot = chart.getCategoryPlot();
        pilot.setRangeGridlinePaint(Color.yellow);
        pilot.setRangeGridlinesVisible(true);
        //setup chart
        ChartPanel c = new ChartPanel(chart);
        
        c.setSize(ChartPannel.getWidth(), ChartPannel.getHeight());
        c.setMouseWheelEnabled(true);

//       p.setLayout(new java.awt.BorderLayout());
        //update panel
        ChartPannel.removeAll();
        ChartPannel.add(c, BorderLayout.CENTER);
        ChartPannel.validate();

    }

    void ChartSP() {
//    List<ThongKe> list = ThongKeDao.SanPham();
        Chart("Thống Kê Sản Phẩm", "Tên Sản Phẩm", "Nghìn Đồng", sp);
    }
    void chartDV(){
         Chart("Thống Kê Dịch Vụ", "Tên Dịch Vụ", "Nghìn Đồng", dv);
    }
    void chartDT(){
        Chart("Thống Kê Doanh Thu", "Ngày", "Nghìn Đồng", thongke);
    
    }
    void init() {
        this.sp = ThongKeDao.SanPham();
        this.dv = ThongKeDao.DichVu();
        this.thongke = ThongKeDao.DoanhThu();
    }

}
